### ISSUE TITLE
could not show friendly name 

### ISSUE THREAD

**Issue by razor9999** [enen92/script.tubecast#23]
I use osmc 18.3

<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:r="urn:restful-tv-org:schemas:upnp-dd">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.0.211:8008</URLBase>
<device>
<deviceType>
urn:dial-multiscreen-org:service:dial:1, urn:dial-multiscreen-org:device:dial:1, ssdp:all
</deviceType>
</friendlyName>
        <manufacturer>Kodi</manufacturer>
        <modelName>Tubecast</modelName>
<UDN>uuid:54b049ff-d851-5186-9d99-b469950f48e9</UDN>
</device>
</root>

**Comment by enen92** [comment]
Please fill a proper bug report
