### ISSUE TITLE
It connects but it does not play..

### ISSUE THREAD

**Issue by rikardfries** [enen92/script.tubecast#42]
on v19 matrix  Kodi KodiSetup-20200408-16d33391-master-x64.exe.
Tried logging in the addon but could not find anylogs.

**Comment by enen92** [comment]
Sorry, my crystal ball is not working well.
Does it throw any error? Provide a log file with debug log enabled in Kodi and debug options enabled in the add-on settings

**Comment by rikardfries** [comment]
you are much to fast for me.. ;) 
[kodi.log](https://github.com/enen92/script.tubecast/files/4460886/kodi.log)

**Comment by enen92** [comment]
Looks like your error is with the youtube addon settings and not really with tubecast. This addon only requests playback from the youtube addon after receiving the playback request from the phone. Can you use the youtube addon standalone?

**Comment by rikardfries** [comment]
I have tried  to run youtube app in the apple phone but no change. I removed the windows firewall, no change, I switched networks, no change.  I checked the youtube settings in the phone. Nothing strange.  It is a nightly Kodi though... I have tried  lots of different things on the Phone. The only thing that Kodi says is "Tubecast, Rikard's phone is connected." Well it is not the end of the world but I thought you might be interested since  am running latest Matrix. It might be the app in the iPhone too... not unlikely at all.

**Comment by enen92** [comment]
I asked if you were able to use the youtube addon in kodi, without using tubecast. I.e., list videos, play, etc. You probably need to configure the youtube addon first.

**Comment by rikardfries** [comment]
Yes now I am. 
It consistently said ""youtube key expired bad request"" so I had to create new personal ones.
Now it is working just fine.

**Comment by rikardfries** [comment]
But now since 1.4.3 it works perfectly. 
It is soo cool.
I must ask what made the difference.. python version ? or autostart ?
Thank you so much,  I can see that you are doing lots of other stuff, but I do appreciate your time spent on this.

**Comment by rikardfries** [comment]
Works perfect thanks for the help.
