### ISSUE TITLE
Need to bump requests package version in requirements

### ISSUE THREAD

**Issue by chulucninh09** [enen92/script.tubecast#51]
Hi, I just found out for my fresh install kodi + tubecast, the tubecast server is unable to start due to the exception when handling context of Response object in requests package.

Digging deeper and it turned out requests==2.12.4 didn't implement `__enter__` and `__exit__` magic. After updated requests package to 2.22.0 (the lastest in Kodi repo though), I was able to start tubecast server.

So, due to my limited knowledge in Kodi add-on, I think the problem persists because your requirements.txt file for test doesn't lock package version like addon.xml, making the code still passes the test but doesn't work in Kodi.

To solve this, I propose 2 action:
1. Bump requests package in addon.xml to 2.22.0
2. Lock package version in requirements.txt for test for more concrete future tests

**Comment by sovaby** [comment]
Make patch please .
