### ISSUE TITLE
Casting doesn't work on new android YouTube app

### ISSUE THREAD

**Issue by spirgiuz** [enen92/script.tubecast#53]
I recently updated my android YouTube app to 16.22.35 and now if I try to connect the youtube app to tubecast addon, it just hangs on connecting. If I downgrade the android YouTube app it starts working again. Do you maybe know what the issue is and if it would be possible to use the newest version of the android app with the tubecast addon?

**Comment by patrickkfkan** [comment]
Hi there,

I don't use Kodi myself but I came across this issue with a [Node module](https://github.com/patrickkfkan/yt-cast-receiver) I developed that was deeply inspired by TubeCast (and so 'borrows' a fair bit of code from it :).

The reason why this happened is you need to pass a `device_id` during the stage where you register the pairing code. Previous YouTube app versions did not seem to check for this, but the current version does. To be specific, the lines that do this are:

https://github.com/enen92/script.tubecast/blob/matrix/resources/lib/tubecast/youtube/app.py#L226-L238

So changing this line:

```
"screen_name": self.default_screen_name
```

to this:

```
"screen_name": self.default_screen_name,
"device_id":  [I used uuid here, but for Kodi perhaps get_device_id()?]
```

should do the trick - at least it did in my case.

As I said, I don't use Kodi so I feel less inclined to submit a PR without testing the change first. So it would be great if you could try this on your end or get someone who's willing to do this (in the [forums thread](https://forum.kodi.tv/showthread.php?tid=329153) perhaps?). Anyway, good luck!

**Comment by spirgiuz** [comment]
@patrickkfkan I just tried it, worked like a charm, thank you very much.

**Comment by ivanich** [comment]
@patrickkfkan Can confirm that it does work, thank you.

**Comment by patrickkfkan** [comment]
That's good to know and thanks @ivanich for the PR~

**Comment by giaur500** [comment]
Is this addon still maintained?

**Comment by baimont** [comment]
@patrickkfkan thanks! just tested this and it works.

**Comment by giaur500** [comment]
Will it work on Kodi 18?

**Comment by baimont** [comment]
> Will it work on Kodi 18?

Yes. My test was on 18.7

**Comment by giaur500** [comment]
Can I pull and use the same version? Branch is for Matrix

**Comment by archiebunker3000** [comment]
Making the change suggested by @ivanich works like a charm.

https://github.com/ivanich/script.tubecast/commit/43800d592755a611d9313d762c755f755bd175ee

**Comment by speising** [comment]
after applying this to my krypton system, i can connect, but get "no stream detected" errors when i try to actually play a video.

**Comment by patrickkfkan** [comment]
@speising , I'm not sure if this is a problem with TubeCast, which only handles the connection and communication of commands between Kodi and the YouTube app. Video playback is actually delegated to tubed, which has recently been updated to handle the way the streams are fetched in response to recent YouTube changes. Is the tubed update available for Kodi Krypton?

**Comment by speising** [comment]
@patrickkfkan , you're right, although it is the youtube plugin on krypton.

**Comment by spirgiuz** [comment]
Seems like it broke again in the same way with 16.25.38. Stuck on connecting again.

**Comment by boogie666** [comment]
> Hi there,
> 
> I don't use Kodi myself but I came across this issue with a [Node module](https://github.com/patrickkfkan/yt-cast-receiver) I developed that was deeply inspired by TubeCast (and so 'borrows' a fair bit of code from it :).
> 
> The reason why this happened is you need to pass a `device_id` during the stage where you register the pairing code. Previous YouTube app versions did not seem to check for this, but the current version does. To be specific, the lines that do this are:
> 
> https://github.com/enen92/script.tubecast/blob/matrix/resources/lib/tubecast/youtube/app.py#L226-L238
> 
> So changing this line:
> 
> ```
> "screen_name": self.default_screen_name
> ```
> 
> to this:
> 
> ```
> "screen_name": self.default_screen_name,
> "device_id":  [I used uuid here, but for Kodi perhaps get_device_id()?]
> ```
> 
> should do the trick - at least it did in my case.
> 
> As I said, I don't use Kodi so I feel less inclined to submit a PR without testing the change first. So it would be great if you could try this on your end or get someone who's willing to do this (in the [forums thread](https://forum.kodi.tv/showthread.php?tid=329153) perhaps?). Anyway, good luck!

I've testing this and by manually patching the specified file on two kodi's both at latest version just last night (note that this is needed in two places in the same file, just find the other dict that has the `screen_name` prop, in the `_get_pairing_code` function) and it works like a charm.

Note that both of my systems are running Kodi via OSMC.

**Comment by enen92** [comment]
Will be part of the next release, thanks for the contributions!
