### ISSUE TITLE
When not connected for a while, the TV disappear within Youtube APP

### ISSUE THREAD

**Issue by thelittlecousin** [enen92/script.tubecast#6]
My Youtube on Android didn't and doesn't detect the TV, so I did the manual paring with the app and it worked, connected with no issues. But when I disconnect it and close the YouTube on Android APP  for a while and come back later it cannot be seen. I also found out that playing Playlists doesn't work, it keeps writing Connecting to TV.

So each time I must manually pair and reuse the paring code to link it. It does detect it as another TV since it keeps adding up a number on the YouTube Android APP beside the tv.

**Comment by enen92** [comment]
Thanks for the feedback. I now finally have a working phone again so I'll look into this soon!

**Comment by siku2** [comment]
@enen92, do you think this would be fixed by #12?
If so I think this issue should be closed in favour of the latter.

**Comment by enen92** [comment]
I was never able to reproduce this. I guess it should be closed and reopened if still valid.
