### ISSUE TITLE
Kodi 18 Support

### ISSUE THREAD

**Issue by neo-neo1** [enen92/script.tubecast#67]
Since Kodi 18 support was stopped the 1.4.6 version currently on official Kodi 18 Repo is mostly broken due to missing PRs only Kodi 19 Matrix version has. 

Many of us are unable to use to Kodi 19 Matrix. For example, LibreELEC and CoreELEC users on Rasp Pi 3B and dozens of others boards lack Kodi 19 support. 

It’s installable but functionality is broken due to missed PRs which fixed crucial issues. Please reconsider, I will even donate. This is a very important app with no alternatives. Thank you in advance!

**Comment by montvid** [comment]
wow, no kodi 18 support? I want to use my rpi 1 :(

**Comment by chapperino** [comment]
It is certainly disappointing this incredibly useful app has rendered a very active user base as obsolete. 

No one should be forced to upgrade a Rasp Pi 3 to Rasp Pi 4 just to use this app, especially in the middle of a silicon shortage hiking prices and availability. Good luck trying to find a Rasp Pi 4 for sale.

**Comment by montvid** [comment]
[LibreELEC-RPi.arm-9.2.6.img.gz](https://releases.libreelec.tv/LibreELEC-RPi.arm-9.2.6.img.gz) seems basic functionality on kodi 18.9 i.e. casting a video works with tubecast 1.4.6. So far so good.

**Comment by chapperino** [comment]
> [LibreELEC-RPi.arm-9.2.6.img.gz](https://releases.libreelec.tv/LibreELEC-RPi.arm-9.2.6.img.gz) seems basic functionality on kodi 18.9 i.e. casting a video works with tubecast 1.4.6. So far so good.

Unfortunately, not for me and many others

**Comment by montvid** [comment]
@chapperino try the linked build for rpi 1. It should work on rpi 3 too.

**Comment by chapperino** [comment]
> @chapperino try the linked build for rpi 1. It should work on rpi 3 too.

I’m quite familiar with LibreELEC and have tried numerous times.

**Comment by netty0** [comment]
> [LibreELEC-RPi.arm-9.2.6.img.gz](https://releases.libreelec.tv/LibreELEC-RPi.arm-9.2.6.img.gz) seems basic functionality on kodi 18.9 i.e. casting a video works with tubecast 1.4.6. So far so good.

Few things. 

1) Why use old version of 9.2.6 as 9.2.8 is the current of LibreELEC 9.x.x branch. 9.2.8 is Kodi 18.9 and has many fixes and improvements. 

2) Regrettably this Addon does not work for me on any version of Kodi 18 using LibreELEC. It has in years past but stopped functioning. 

3) Looking at releases and PRs it does seem 1.4.6 lacks many fixes. If it works for you then likely you aren’t affected.

**Comment by prahal** [comment]
Could this bug be closed?
LibreElec 11 from 2024 with Kodi 20 is supported on Raspberry Pi3 https://libreelec.tv/downloads/raspberry/
and LibreElec 10 from 2023  with Kodi 19 is supported on RPi 1.
Or maybe RPi 3B is not supported?

I mean I don't know if even if a new release of script.tubecast for Kodi 18 could be uploaded to Kodi repositories.
All in all, it might be better to add support for a board for a new LibreElec than ask the Kodi repositories maintainer to update repositories which is frozen.
