### ISSUE TITLE
Missing dependency when installed on Xbian

### ISSUE THREAD

**Issue by ghost** [enen92/script.tubecast#69]
Xbian version: `XBian 10.0 - Bullseye - 20220401-0 - Bleeding Edge, 2012-2022`
Kodi version: `19.4.0`

Original issue was that Youtube app does not find the Kodi device.

While debugging, combining the SSDP server code and it's surrounding code into a single file, I noticed this part (from utils.py) giving me an error:
```
from bottle import SimpleTemplate
```

Resolved by installing python3-bottle manually with `apt install python3-bottle` and now my Kodi device is found by Youtube app.

Should Tubecast addon come bundled up with python3-bottle or is this an Xbian issue?

**Comment by enen92** [comment]
bottle comes from the kodi repo when you install the addon. Did you install it via the interface or via zip file?

**Comment by ghost** [comment]
> bottle comes from the kodi repo when you install the addon. Did you install it via the interface or via zip file?

I installed with the Kodi interface "install from repository".

EDIT:
I checked my `.kodi/addons` and found `script.module.bottle` there, so it should be installed as far as I know.

**Comment by ghost** [comment]
After a bit more testing I think it was just a lucky coincidence that installing `python3-bottle` got the device discovery working.

I tried uninstalling and reinstalling the package and now it seems that the device cannot be found either way.

I will try to run more tests to figure out the actual problem, closing this issue for now..
