### ISSUE TITLE
DELETE request from Chrome uses incorrect path and returns 404

### ISSUE THREAD

**Issue by nickrbogdanov** [enen92/script.tubecast#71]
When I cast from Chrome on my Macbook, Tubecast is extremely flaky.  I looked in Wireshark and saw one obvious anomaly:

![image](https://user-images.githubusercontent.com/63979903/196562816-0dd2b668-5707-4d68-895f-a98bd170776e.png)

This path isn't handled by Tubecast, so it returns 404 and that prevents Chrome from getting back into a state where it can cast a new video.

Tubecast is matching a path of `/apps/YouTube/web-1`, presumably based on the Application Information Response string hardcoded into the program:

```
    @property
    def connected(self):
        return '''<service xmlns="urn:dial-multiscreen-org:schemas:dial">
                    <name>YouTube</name>
                    <options allowStop="true"/>
                    <servicedata xmlns="urn:chrome.google.com:cast">
                        <connectionSvcURL></connectionSvcURL>
                        <protocols>
                            <protocol>ramp</protocol>
                        </protocols>
                    </servicedata>
                    <state>running</state>
                    <activity-status xmlns="urn:chrome.google.com:cast">
                        <description>YouTube Receiver</description>
                    </activity-status>
                    <link rel="run" href="web-1"/>
                </service>'''
```

It's not clear to me where the bug is.  However, the latest version of the [DIAL specification](http://www.dial-multiscreen.org/dial-protocol-specification) says that the response uses the same `href` and `rel` properties:

![image](https://user-images.githubusercontent.com/63979903/196563040-fa9d7be6-08dc-4612-b823-d839cc2e1e41.png)

so if we followed their example and then changed `_setup_routes()` to hook `/apps/YouTube/run` instead of `/apps/YouTube/web-1`, that would fix the problem.

Your thoughts?

**Comment by enen92** [comment]
thanks, will try to take a look
