### ISSUE TITLE
Youtube's latest playback modifications broke Tubecast

### ISSUE THREAD

**Issue by tpaniaki** [enen92/script.tubecast#85]
Kodi 20.5
Tubecast 1.5.0

As described in the title:

![Capture d'écran Deepin_zone de sélection _20240401194111](https://github.com/enen92/script.tubecast/assets/25780374/20c85302-53b3-4a63-ae78-f5ea18f8e5ca)

**Comment by andrewramsay** [comment]
Updating the YouTube addon to the latest beta version fixed this for me: https://github.com/anxdpanic/plugin.video.youtube/releases

**Comment by tpaniaki** [comment]
Yep. Closing.
